apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: DOCKERFILE
      type: string
      description: Path to the Dockerfile
    - name: IMAGE
      type: string
      description: Name of the image to be built
    - name: CONTEXT
      type: string
      description: The build context
    - name: DOCKER-CREDENTIALS
      type: string
      description: Name of the Docker credentials secret
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable
      script: |
        buildah bud --pull --file $(params.CONTEXT)/$(params.DOCKERFILE) --tag $(params.IMAGE) $(params.CONTEXT)
        buildah push --creds=$(params.DOCKER-CREDENTIALS) $(params.IMAGE)
