apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      description: The git repository URL
      type: string
    - name: revision
      description: The git revision to checkout
      type: string
      default: "main"
    - name: output
      description: The directory where the repo will be cloned
      type: string
      default: "/workspace/output"
  steps:
    - name: clone
      image: "alpine/git"
      script: |
        git clone $(params.url) -b $(params.revision) $(params.output)
