apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
    - name: DOCKER-CREDENTIALS
      type: string
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: output
          value: "/workspace/output"

    - name: build-and-push-image
      runAfter:
        - clone-repo
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: CONTEXT
          value: "/workspace/output"
        - name: DOCKER-CREDENTIALS
          value: $(params.DOCKER-CREDENTIALS)
