# Use a more recent Ruby version
FROM ruby:3.1.2

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies and Node.js
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs

# Install bundler version compatible with Ruby 3.2.2
RUN gem install bundler -v 2.4.22

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Install project dependencies
RUN bundle install

# Copy the rest of the application code into the container
COPY . .

# Expose the port the Rails app runs on
EXPOSE 3000

# Start the Rails application
CMD ["rails", "server", "-b", "0.0.0.0"]
