version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://harsh:your_password@db/harsh_production"
    volumes:
      - .:/app

  db:
    build:
      context: ./database
      dockerfile: dockerfile
    environment:
      POSTGRES_USER: harsh
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: harsh_production
