# Use a more recent Ruby version
FROM ruby:3.1.2

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies and Node.js
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs

# Install bundler version compatible with Ruby 3.1.2
RUN gem install bundler -v 2.4.22

# Clone the repository
RUN git clone https://github.com/harshrajurkar/Budget-App-ruby .

# Change to the cloned repository directory
WORKDIR /app/Budget-App-ruby

# Install project dependencies
RUN bundle install

# Expose the port the Rails app runs on
EXPOSE 3000

# Start the Rails application
CMD ["rails", "server", "-b", "0.0.0.0"]
